#!/usr/bin/env python3
"""build_roles.py — compile the role notes into runnable agents.

Source: 01 - Company/Roles/*.md   Output: .claude/agents/<slug>.md
Edit the role note, never the agent file: the next build overwrites it.
"""
from __future__ import annotations
import io, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import framework as F

BANNER = "<!-- generated by .ops/scripts/build_roles.py — edit the role note, not this file -->"


def build(root):
    roles = F.notes(root, F.ROLES_DIR)
    if not roles:
        raise SystemExit("build_roles: no role notes found in " + F.ROLES_DIR)
    os.makedirs(os.path.join(root, F.AGENTS_DIR), exist_ok=True)
    written = []
    for r in roles:
        slug = r.get("slug") or r["_name"].lower().replace(" ", "-")
        owns = r.get("owns") or []
        never = r.get("never") or []
        dept = r.get("department")
        desc = (f"{r.get('name', r['_name'])} — {r.get('authority','prepare')} authority. "
                + (f"Leads the {dept} department. " if dept else "Company-wide, not tied to one department. ")
                + ("Owns: " + "; ".join(owns[:3]) + ". " if owns else "")
                + ("Never: " + "; ".join(never) + ". " if never else "")
                + f"Reports to {r.get('reports_to','you')}.")
        green = "\n".join(f"- {g}" for g in (r.get("green_list") or [])) or "- (nothing yet)"
        no = "\n".join(f"- {n}" for n in never) or "- (nothing yet)"
        zones = ", ".join(f"`{z}`" for z in (r.get("writes") or [])) or "nothing yet"
        text = (f"---\nname: {slug}\ndescription: \"{desc}\"\n---\n{BANNER}\n\n"
                f"{r['_body'].strip()}\n\n## Your authority\n\n"
                + (f"You answer for the **{dept}** department; see `01 - Company/Departments/{dept}.md`. "
                   f"Another department's question is not yours — hand it back.\n\n" if dept else "")
                + f"Default level: **{r.get('authority','prepare')}**. "
                f"You may write in: {zones}.\n\n"
                f"### You may do these without asking\n\n{green}\n\n"
                f"### You may never\n\n{no}\n\n"
                f"Anything not on the first list, you prepare and hand to a person. "
                f"Read `CLAUDE.md` at the vault root first — it is the contract you inherit, "
                f"and where it and this file disagree, the contract wins and this file is stale.\n")
        p = os.path.join(root, F.AGENTS_DIR, slug + ".md")
        io.open(p, "w", encoding="utf-8", newline="\n").write(text)
        written.append(slug)
    return written


if __name__ == "__main__":
    root = sys.argv[1] if len(sys.argv) > 1 else os.getcwd()
    w = build(root)
    print(f"built {len(w)} agents from the role notes: {', '.join(w)}")
